# specific branch build
trigger:
  branches:
    include:
    - stable/*

jobs:
# Lunux builds
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 120
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      pip install --upgrade pip
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
      ./.ci/run.sh
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
      CONAN_REMOTES: https://api.bintray.com/conan/pss146/public-conan
      CONAN_UPLOAD: https://api.bintray.com/conan/pss146/public-conan
      CONAN_USERNAME: pss146
      CONAN_BUILD_POLICY: missing
      CONAN_ARCHS: x86_64
  strategy:
    matrix:
      GCC5:
        CONAN_GCC_VERSIONS: 5
        CONAN_DOCKER_IMAGE: conanio/gcc5
      GCC6:
        CONAN_GCC_VERSIONS: 6
        CONAN_DOCKER_IMAGE: conanio/gcc6
      GCC7:
        CONAN_GCC_VERSIONS: 7
        CONAN_DOCKER_IMAGE: conanio/gcc7
      GCC8:
        CONAN_GCC_VERSIONS: 8
        CONAN_DOCKER_IMAGE: conanio/gcc8
      CLANG6.0:
        CONAN_CLANG_VERSIONS: 6.0
        CONAN_DOCKER_IMAGE: conanio/clang60
      CLANG7.0:
        CONAN_CLANG_VERSIONS: 7.0
        CONAN_DOCKER_IMAGE: conanio/clang7

# MacOS builds
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  timeoutInMinutes: 120
  steps:
  - script: |
      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
      pip install --upgrade pip
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
      ./.ci/run.sh
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
      CONAN_REMOTES: https://api.bintray.com/conan/pss146/public-conan
      CONAN_UPLOAD: https://api.bintray.com/conan/pss146/public-conan
      CONAN_USERNAME: pss146
      CONAN_BUILD_POLICY: missing
      CONAN_ARCHS: x86_64
  strategy:
    matrix:
      CLANG9.1:
        CONAN_APPLE_CLANG_VERSIONS: 9.1
        XCODE_VERSION: 9.4.1
      CLANG10.0:
        CONAN_APPLE_CLANG_VERSIONS: 10.0
        XCODE_VERSION: 10

# Windows builds
- job: Windows
  timeoutInMinutes: 120  
  pool:
    vmImage: $(imageName)
    
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  
  - script: |
      python -m pip install --upgrade pip
      pip.exe install conan --upgrade
      pip.exe install conan_package_tools bincrafters_package_tools
      conan user
    displayName: 'Install conan & package tools'

  - script: |
      python build.py
    displayName: 'Run build'
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
      CONAN_REMOTES: https://api.bintray.com/conan/pss146/public-conan
      CONAN_UPLOAD: https://api.bintray.com/conan/pss146/public-conan
      CONAN_USERNAME: pss146
      CONAN_BUILD_POLICY: missing
      CONAN_ARCHS: x86_64
  
  strategy:
    matrix:
      VS2019:
        imageName: 'windows-latest'
        CONAN_VISUAL_VERSIONS: 16
      VS2017:
        imageName: 'vs2017-win2016'
        CONAN_VISUAL_VERSIONS: 15
